apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quarkus-jvm-hello-app
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: quarkus-jvm-hello-app
                port:
                  number: 8080