kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: quarkus-jvm-helloworld
  labels:
    app: quarkus-jvm-helloworld
    app.kubernetes.io/component: quarkus-jvm-helloworld
    app.kubernetes.io/instance: quarkus-jvm-helloworld
    app.kubernetes.io/name: quarkus-jvm-helloworld
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/mukeshs1306/quarkus-jvm-helloworld:latest'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Local
