apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-netty-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-netty-hello
  template:
    metadata:
      labels:
        app: camel-netty-hello
    spec:

      initContainers:
        - name: init-tls
          image: registry.redhat.io/openshift4/network-tools-rhel8
          command:
            - /bin/sh
            - -c
            - |
              echo "Generating PKCS12 keystore from PEM..."
              mkdir -p /tls-p12
              openssl pkcs12 -export \
                -in /tls/tls.crt \
                -inkey /tls/tls.key \
                -out /tls-p12/server-keystore.p12 \
                -name camel-server \
                -passout pass:password
          volumeMounts:
            - name: tls-secret
              mountPath: /tls
            - name: tls-p12
              mountPath: /tls-p12

      containers:
        - name: camel-netty-hello
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          image: image-registry.openshift-image-registry.svc:5000/demo-test/camel-netty-hello
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          env:
            - name: KEYSTORE_FILE
              value: "/tls-p12/server-keystore.p12"
            - name: KEYSTORE_PASSWORD
              value: "password"
            - name: KEYSTORE_KEY_PASSWORD
              value: "password"
            - name: HTTPS_ENABLED
              value: "true"
          volumeMounts:
            - name: tls-p12
              mountPath: /tls-p12
      volumes:
        - name: tls-secret
          secret:
            secretName: camel-netty-hello-tls
        - name: tls-p12
          emptyDir: {}  # will hold the generated .p12
